imports:
    - { resource: ui/mappers.yaml }

parameters:
    # set via compiler pass
    ezplatform.ezrichtext.alloy_editor: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformRichText\Configuration\Provider\:
        resource: '../../../lib/Configuration/Provider/*'

    EzSystems\EzPlatformRichText\Configuration\Provider\AlloyEditor:
        arguments:
            $alloyEditorConfiguration: '%ezplatform.ezrichtext.alloy_editor%'

    EzSystems\EzPlatformRichText\Configuration\AggregateProvider:
        arguments:
            $providers: !tagged ezrichtext.configuration.provider
