services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformRichText\eZ\REST\FieldTypeProcessor\RichTextProcessor:
        arguments:
            - '@ezrichtext.converter.edit.xhtml5'
        tags:
            - { name: ibexa.rest.field_type.processor, alias: ezrichtext }
