name: CI

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    cs-fix:
        name: Run code style check
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                php:
                    - '8.0'
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: 'pdo_sqlite, gd'
                  tools: cs2pr

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Run code style check
              run: composer run-script check-cs -- --format=checkstyle | cs2pr

    tests:
        name: Tests
        runs-on: ubuntu-22.04
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: pdo_sqlite, gd
                  tools: cs2pr

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run test suite
              run: composer run-script --timeout=600 test

    integration-tests-postgres:
        name: PostgreSQL integration tests
        needs: tests
        services:
            postgres:
                image: postgres:10
                ports:
                    - 5432
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: testdb
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                    --tmpfs /var/lib/postgresql/data
        runs-on: ubuntu-22.04
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: pdo_pgsql, gd
                    tools: cs2pr

            -   uses: ramsey/composer-install@v2
                with:
                    dependency-versions: highest

            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Run integration test suite vs Postgresql
                run: composer run-script integration
                env:
                    DATABASE: "pgsql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/testdb"

    integration-tests-mysql:
        name: MySQL integration tests
        needs: tests
        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3306/tcp
                env:
                    MYSQL_RANDOM_ROOT_PASSWORD: true
                    MYSQL_USER: mysql
                    MYSQL_PASSWORD: mysql
                    MYSQL_DATABASE: testdb
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5
                    --tmpfs=/var/lib/mysql
        runs-on: ubuntu-22.04
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: pdo_mysql, gd
                    tools: cs2pr

            -   uses: ramsey/composer-install@v2
                with:
                    dependency-versions: highest

            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Run integration test suite vs MySQL
                run: composer run-script integration
                env:
                    DATABASE: "mysql://mysql:mysql@127.0.0.1:${{ job.services.mysql.ports[3306] }}/testdb"
    solr-integration:
        name: "Solr integration tests"
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        permissions:
            packages: read
            contents: read
        services:
            solr:
                image: ghcr.io/ibexa/core/solr
                ports:
                    - 8983:8983
                options: >-
                    --health-cmd "solr status"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 10
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none

            - name: Add solr dependency
              run: composer require --no-update "ezsystems/ezplatform-solr-search-engine:^3.3@dev"

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Run integration test suite
              run: composer integration-solr
              env:
                    CORES_SETUP: single
